#!/bin/sh
# $Id: checktree,v 1.3 2006/05/19 10:36:07 goneri Exp $
# Gonéri Le Bouder

DIR=`pwd`
SYNCSECTIONDESC=$DIR"/../syncglobaldesc/syncglobaldesc"
SHEETDIR="../../sheet"

cd $SHEETDIR 
if [ ! -f "global.xml" ]; then
  echo "global.xml doesn't exist in this tree"
  exit 1
fi

# First i try to sync file desc*

for template in `find |grep  template|grep qsos$`;do
  echo "*syncing template $template"
  $SYNCSECTIONDESC -s -l -t global.xml -f $template|| exit 1
done

for dir in `find -mindepth 1 -maxdepth 1 -type d|grep -v CVS`;do 
  echo "*syncing `basename $dir` directory"
  tpl=`find $dir|grep template|grep qsos$`
  for file in `find $dir -type f|grep -v CVS|grep -v template|grep qsos$`;do
    echo "  "`basename $file `
    echo $tpl $file
    $SYNCSECTIONDESC --recreate --more --save --template $tpl --file $file || exit 1
  done
done


exit 1
