#!/bin/sh
# $Id: checktree,v 1.6 2007/03/21 13:25:48 goneri Exp $
# Gonéri Le Bouder

set -e

DIR=`pwd`
SHEETDIR="$DIR/../../sheet"

for i in `find $SHEETDIR -name '*.qsos'`; do
	./checksheet $i 
done

