#!/bin/sh
case ${1} in
	debug)
		rm -rf ~/.raphael.semeteys@atosorigin.com/
		xulrunner application.ini -console -jsconsole
		;;
	help)
		echo "usage: xuleditor [debug]"
		;;
	*)
		rm -rf ~/.raphael.semeteys@atosorigin.com/
		xulrunner application.ini -file ${1}
		;;
esac
